# Generated by Django 5.0.2 on 2024-02-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Esc', 'Escouade'), ('Corp', 'Corporation'), ('All', 'Alliance')], default='Corp', max_length=4)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
