# Generated by Django 5.0.2 on 2024-02-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliance', '0002_remove_corporation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporation',
            name='status',
            field=models.CharField(choices=[('Esc', 'Escouade'), ('Corp', 'Corporation'), ('All', 'Alliance')], default='Corp', max_length=4),
        ),
    ]
