# Generated by Django 5.0.2 on 2024-02-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliance', '0004_group_delete_corporation'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
