# Generated by Django 5.0.2 on 2024-02-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliance', '0005_group_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
