# Generated by Django 5.0.2 on 2024-02-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliance', '0006_alter_group_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('Esc', 'Escouade'), ('Corp', 'Corporation'), ('All', 'Alliance')], default='Corp', max_length=4),
        ),
    ]
