# Generated by Django 5.0.2 on 2024-02-27 01:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actu',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution'),
        ),
    ]
