# Generated by Django 5.0.2 on 2024-03-03 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliance', '0007_alter_group_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='main_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='group',
            name='rsi_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='secondary_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_username', models.CharField(max_length=100)),
                ('rsi_handle', models.CharField(max_length=100)),
                ('leader', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alliance.group')),
            ],
        ),
    ]
