# Generated by Django 5.0.2 on 2024-02-25 05:52

import discordlogin.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordlogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='discorduser',
            managers=[
                ('objects', discordlogin.managers.DiscordUserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='discorduser',
            old_name='discord_id',
            new_name='username',
        ),
    ]
