# Generated by Django 5.0.2 on 2024-02-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordlogin', '0002_alter_discorduser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
